{"name": "Запуск приложения и авторизация,тап на Эфир", "status": "failed", "statusDetails": {"message": "AssertionError: ('open_efir',) not in [('autotake_on',), ('driver_sign_in',), ('efir_on',), ('fast_login_click',), ('fast_search_disable',), ('fast_search_enable',), ('fast_search_tap',), ('filter_off',), ('free_disable',), ('free_enable',), ('login_click',), ('login_failed',), ('LoginFailed',), ('LoginScreenShown',), ('open_filters_page',), ('settings_font_size',), ('sound_broadcast',), ('switch_off_all_filter',)]\n", "trace": "  File \"c:\\users\\user\\pycharmprojects\\pythonproject6\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject6\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\OpenEfirTest.py\", line 44, in checkevents\n    raise AssertionError(f'{expected_event_type} not in {actual_event_types}')\n"}, "steps": [{"name": "Given Запуск приложения и авторизация перед открытием Эфира", "status": "passed", "steps": [{"name": "Click on button Enter before authorisation.", "status": "passed", "start": 1627923962114, "stop": 1627923962114}, {"name": "Enter the code to go to env. selection screen.", "status": "passed", "start": 1627923968478, "stop": 1627923968478}, {"name": "Enter Url a required env.", "status": "passed", "start": 1627923975368, "stop": 1627923975368}, {"name": "Enter Url a AnalyticServis.", "status": "passed", "start": 1627924006496, "stop": 1627924006496}, {"name": "Click to confirm the env selection.", "status": "passed", "start": 1627924007026, "stop": 1627924007026}, {"name": "Enter login users.", "status": "passed", "start": 1627924012728, "stop": 1627924012728}, {"name": "Enter password users.", "status": "passed", "start": 1627924018316, "stop": 1627924018316}, {"name": "Click on loginButton for authorisation in App.", "status": "passed", "start": 1627924019517, "stop": 1627924019517}, {"name": "Close pop-up info Attention.", "status": "passed", "start": 1627924039436, "stop": 1627924039436}, {"name": "Close pop-up info Order chain.", "status": "passed", "start": 1627924043054, "stop": 1627924043054}], "start": 1627923959909, "stop": 1627924046057}, {"name": "When Тап на Эфир", "status": "passed", "steps": [{"name": "Click on Button Efir.", "status": "passed", "start": 1627924047132, "stop": 1627924047132}], "start": 1627924046057, "stop": 1627924052144}, {"name": "Then Проверить в БД ивент open_efir", "status": "failed", "statusDetails": {"message": "AssertionError: ('open_efir',) not in [('autotake_on',), ('driver_sign_in',), ('efir_on',), ('fast_login_click',), ('fast_search_disable',), ('fast_search_enable',), ('fast_search_tap',), ('filter_off',), ('free_disable',), ('free_enable',), ('login_click',), ('login_failed',), ('LoginFailed',), ('LoginScreenShown',), ('open_filters_page',), ('settings_font_size',), ('sound_broadcast',), ('switch_off_all_filter',)]\n", "trace": "  File \"c:\\users\\user\\pycharmprojects\\pythonproject6\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject6\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\OpenEfirTest.py\", line 44, in checkevents\n    raise AssertionError(f'{expected_event_type} not in {actual_event_types}')\n"}, "start": 1627924052144, "stop": 1627924072445}], "start": 1627923945886, "stop": 1627924085509, "uuid": "3c640b5a-ee7c-4325-a3cd-2f41e902ee89", "historyId": "04a92fd0c799436d2abd9ee9b755cafa", "fullName": "Проверка ивента open_efir при открытии Эфира на главном экране: Запуск приложения и авторизация,тап на Эфир", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Проверка ивента open_efir при открытии Эфира на главном экране"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}